# Generated by Django 5.2.8 on 2025-12-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
