# Generated by Django 5.2.8 on 2025-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_alter_subscription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
